CREATE TABLE SURVEY (

	ID_SURVEY INT NOT NULL GENERATED ALWAYS AS IDENTITY,
	ACTIVITY_ID INT NOT NULL, 
	ANSWERS JSON NOT NULL,
	CREATED_AT TIMESTAMP NOT NULL,
	PRIMARY KEY(ID_SURVEY),
	CONSTRAINT FK_ACTIVIY
		FOREIGN KEY(ID_ACTIVITY)
			REFERENCES ACTIVITY(ID_ACTIVITY)
);

SELECT * FROM SURVEY;

