CREATE TABLE ACTIVITY (
	
	ID_ACTIVITY INT NOT NULL GENERATED ALWAYS AS IDENTITY,
	ID_PROPERTY INT NOT NULL,
	SCHEDULE TIMESTAMP NOT NULL,
	TITLE VARCHAR(255),
	CREATED_AT TIMESTAMP NOT NULL,
	UPDATE_AT TIMESTAMP NOT NULL,
	STATUS VARCHAR(35),
	PRIMARY KEY (ID_ACTIVITY),
	CONSTRAINT FK_PROPERTY 
		FOREIGN KEY(ID_PROPERTY)
			REFERENCES PROPERTY(ID_PROPERTY)
			
);

SELECT * FROM ACTIVITY;